spring :
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/junstagram
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

custom:
  profileImg:
    path: '/Users/jun/Study/profile_imgs/'
  post:
    path: '/Users/jun/Study/uploads/'

