server :
  port : 8081

spring :
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/junstagram
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 755707363142736
            client-secret: ddb957a28a3ea05db67dc331eff612fd
            scope: public_profile,email
logging:
  level:
    org.hibernate.SQL: debug

custom:
  profileImg:
    path: '/Users/jun/Study/profile_imgs/'
  post:
    path: '/Users/jun/Study/uploads/'


